### ISSUE TITLE
Podling scan reports errors

### ISSUE THREAD

**Issue by kw217** [apache/incubator-pekko#110]
The podling scan at https://incubator.apache.org/clutch/pekko.html currently reports a long list of errors. This seems to be because the project site at http://pekko.incubator.apache.org/ is currently missing.

* Creating the site is already covered by #99 
* This issue covers following the guidance at https://infra.apache.org/project-site.html to ensure the necessary data is provided on the landing page (i.e., currently, `docs/src/main/paradox/index.md`

**Comment by kw217** [comment]
> the web site will be https://pekko.apache.org/ and this is allowed - if you check the podling scan output.

Thanks, corrected in description.

**Comment by kw217** [comment]
The Apache Pekko landing page https://github.com/apache/incubator-pekko/blob/main/docs/src/main/paradox/index.md is currently just a TOC page (rendered: https://pekko.staged.apache.org/).

There are two ways we could ensure the project landing page meets the [Apache project site requirements](https://infra.apache.org/project-site.html):
* We could add content to the existing TOC page, so it has the intro material and then the TOC below that.
* We could replace the existing TOC page with the intro material, move the TOC to a new page, and add a link from the landing page.

Does anyone have a preference?

**Comment by pjfanning** [comment]
We are likely to clone sbt-paradox - we have an empty repo earmarked and an issue open. My preference would be to have a collapsible tab on all pages with all the required links.

**Comment by sam-byng** [comment]
Update on the status of this issue:

The podling scan at https://incubator.apache.org/clutch/pekko.html is still failing with errors stating that the Text and URIs to the ASF websites are not present. See https://whimsy.apache.org/pods/project/pekko .

From looking at the pekko docs homepage (https://pekko.apache.org/docs/pekko/current/), at least some of these are present, however the errors are still raised.

**Root cause**:

To me it looks like the issue may be related to the fact that our homepage URI is not actually https://pekko.apache.org (per expecatation from the crawler code) but is https://pekko.apache.org/docs/pekko/current/ (since we're matching the behaviour performed by the non-apache sbt-paradox [homepage](https://developer.lightbend.com/docs/paradox/current/) which also has a redirect to /docs/paradox/current). 
The redirect from https://pekko.apache.org -> https://pekko.apache.org/docs/pekko/current/ might be causing an issue 


Potentially it is attempting to crawl over the webpage https://pekko.apache.org/ , however the actual homepage is at https://pekko.apache.org/docs/pekko/current/ (which is what the initial link redirecting to)

**Comment by pjfanning** [comment]
Thanks for your interest. We are working closely with the Incubator PMC. We are aware of the issues. We will not do a release until we meet the requirements of the PMC. This release is many months away.

**Comment by sam-byng** [comment]
Thanks for the quick response. Can we add this task into the 1.0.0 milestone so that it is tracked there?
